# -*- coding: utf-8 -*-
"""programacion1-12026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WDtFD1WX_VM-ispvy39u8pvY37jg2zOJ

# Corte 1

Lección 1 - Fundamentos de python
"""

print("Hola mundo")

nombre=input("¿Cual es tu nombre?")

print("Hola mundo de", nombre)

nombre='Silvia'
edad=28
altura=1.67
correo="julianamroa@gmail.com"
Soltero=True

print("Tipos de dato:")
print(type(nombre))
print(type(Soltero))
print(type(altura))
print(type(correo))
print(type(edad))

print("Hola", nombre, "tienes", edad-10)

"""CLASE 2 (24/08/2026)"""

#Operaciones matematicas

vab1=20
vab2=15

print(vab1 + vab2)

print("La suma es:", vab1 + vab2)

vab1 = 20
vab2 = 15

suma= vab1 + vab2

print(vab1,"+",vab2, "=", suma)

vab1 = 20
vab2 = 15

suma= vab1 + vab2
resta= vab1 - vab2
multi= vab1 * vab2
divi= vab1 / vab2

print(vab1,"+",vab2, "=", suma)
print(vab1,"-",vab2, "=", resta)
print(vab1,"*",vab2, "=", multi)
print(vab1,"/",vab2, "=", divi)

nombre = input("Indicanos tu nombre: ")

print("Por favor indicame 3 notas para calcular el promedio")

nota1 = float(input("Nota 1: "))
nota2 = float(input("Nota 2: "))
nota3 = float(input("Nota 3: "))
suma=(nota1+nota2+nota3)
promedio=suma/3
print("suma de notas", suma)
print("El promedio de notas es", promedio)

"""**RETO 1**

Una tienda de tecnología necesita calcular el valor de una compra realizada por un cliente. Para ello, se requiere desarrollar un programa en Python que permita registrar la cantidad de productos comprados y el precio unitario de cada producto.

El programa debe calcular y mostrar:

* El subtotal de la compra. - Santiago Peña Rua
* El valor del IVA (19%). - Nicolas Villamizar
* El total a pagar.
* El valor correspondiente a un descuento del 10% sobre el subtotal.
* El total final después de aplicar el descuento y sumar el IVA.
"""

print("bIENVENIDO A LA TIENDA Chucu")
nombredelproducto="Bocadillo"
Cantidad=int(input("¿Cuantos bocadillos compraste?"))
PrecioBocadillo=4500
subtotal=PrecioBocadillo * Cantidad
print("El subtotal es",subtotal)

#Parte 2 - Nicolas Villamizar
vabIVA = 19 / 100
costoIVA = vabIVA * subtotal
print("costo del IVA 19%", costoIVA)

#Parte 3

TotalPagar = subtotal + costoIVA
print("Total a pagar: $", TotalPagar)

"""SOLUCION EJERCICIO 1
Ejercicio 1 — Cafetería universitaria (2,5 puntos)

Una cafetería universitaria desea automatizar el cálculo de una compra. El programa debe solicitar al usuario la cantidad de productos comprados y el precio unitario de cada producto.

El programa debe:

* a. (0,5 puntos): Calcular y mostrar el subtotal de la compra.
* b. (0,5 puntos): Calcular y mostrar el 10% de descuento aplicado sobre el subtotal.
* c. (0,5 puntos): Calcular y mostrar el IVA del 19% sobre el subtotal.
* d. (0,5 puntos): Calcular y mostrar el total a pagar después del descuento y antes del IVA.
* e. (0,5 puntos): Calcular y mostrar el valor final a pagar, incluyendo el IVA.
"""

print("BIENVENIDOS A LA CAFETERIA UNIVERSIDAD")
cantidad=int(input("¿cuantos productos deseas comprar?"))
valorproducto=float(input("¿cual es el precio del producto"))

subtotal= cantidad * valorproducto
print("subtotal",subtotal)

descuento= 10/100
print("descuento",descuento)

IVA= 19/100
print("IVA",IVA)

TOTAL_descuento= descuento * subtotal
print("TOTAL_descuento",TOTAL_descuento)

TOTAL_PAGAR=subtotal-TOTAL_descuento
print("TOTAL_PAGAR",TOTAL_PAGAR)

RESULTADO_IVA=TOTAL_PAGAR*IVA
print("RESULTADO_IVA",RESULTADO_IVA)

TOTAL_PAGAR_IVA=TOTAL_PAGAR+RESULTADO_IVA
print("TOTAL_PAGAR_IVA",TOTAL_PAGAR_IVA)

TOTAL_FINAL=TOTAL_descuento+TOTAL_PAGAR_IVA
print("TOTAL_FINAL",TOTAL_FINAL)



"""Ejercicio 2 — Viaje en automóvil (2,5 puntos)

Una persona desea calcular cuánto dinero gastará en combustible durante un viaje. Para ello, conoce la distancia del viaje en kilómetros, el rendimiento del automóvil en kilómetros por litro y el precio de un litro de gasolina.

El programa debe:

* a. (0,5 puntos): Calcular y mostrar la cantidad de litros de gasolina necesarios para realizar el viaje.
* b. (0,5 puntos): Calcular y mostrar el costo total del combustible.
* c. (0,5 puntos): Calcular y mostrar el costo del combustible si el precio aumenta un 8%.
* d. (0,5 puntos): Calcular y mostrar cuánto corresponde pagar si el costo total se divide entre 3 personas.
* e. (0,5 puntos): Calcular y mostrar el costo total del viaje ida y vuelta.

Calificación total: 5,0 puntos

* Ejercicio 1: 2,5 puntos
* Ejercicio 2: 2,5 puntos
"""

distancia= float(input("Dame la distancia del viaje: "))
rendimiento= float(input("Dame el rendimiento del automovil: "))
precio_litro_gasolina = float(input("Dame el precio de litro de la gasolina: "))

gasolina_necesaria = distancia/rendimiento

print("Para ", distancia, " km con rendimiento de ", rendimiento, " km/l necesitamos ", gasolina_necesaria, " litros de gasolina")

costo_gasolina=gasolina_necesaria*precio_litro_gasolina

print("El precio a pagar para ", gasolina_necesaria, "litros es de ", costo_gasolina)

costo_gasolina_aumenta= costo_gasolina*0.8
costo_final_gasolina = costo_gasolina + costo_gasolina_aumenta

print("El costo final de la gasolina tras el aumento es $", costo_final_gasolina)

print("El costo por persona para este viaje es $", costo_final_gasolina/3)

print("El costo del viaje ida y vuelta total es $", costo_final_gasolina*2)

print("El costo del viaje ida y vuelta total por persona es $", (costo_final_gasolina*2)/3)

distacia =float(input("distacia del viaje en km"))
print("¿cual es la distacia del viaje en km?", distacia)
rendimiento_automovil = float(input("el rendimiento del automovil"))
print("¿cual es el rendimiento del automovil en km x L?",rendimiento_automovil)
precio_litro_gasolina = float(input("precio litro gasolina"))
print("¿cual es el precio L de la gasolina?", precio_litro_gasolina)
litro_necesarios_de_gasolina = distacia / rendimiento_automovil
print("litros_necesarios_de_gasolina",litro_necesarios_de_gasolina )
costototal= litro_necesarios_de_gasolina * precio_litro_gasolina
print("El costo total del combustible es de: ", costototal)


#Ejercicio david
precio_aumento_gasolina=(precio_litro_gasolina * 8/100)
precio_litro_gasolina=precio_litro_gasolina + precio_aumento_gasolina


#Ejercicio natalia
costo_para3 = (litro_necesarios_de_gasolina * precio_litro_gasolina)/3
print("El valor a pagar para cada uno es: $" , costo_para3)

ida_y_vuelta = distancia *2 *precio_de_gasolina

"""Clase 07/09 - Ciclos for y while"""

num1 = int(input("Dame un numero: "))
num2 = int(input("Dame un numero: "))
num3 = int(input("Dame un numero: "))

suma=num1+num2+num3

print("La suma es: ", suma)

cuantosNumerosSumar = int(input("¿Cuantos numeros deseas sumar? "))

acumuladoSuma=0

for i in range(cuantosNumerosSumar):
  numero = int(input("Dame el numero que quieres sumar"))
  acumuladoSuma = acumuladoSuma + numero

print("La suma es ", acumuladoSuma)

for i in range(5):
  print("i=",i)

for i in range(3):
  print("Esta por dentro del bucle: ", i, "vez")
print("Está por fuera")

#Caso 1
print("#Caso 1")
for i in range(5):
  print("i=", i)

#Caso 2
print("#Caso 2")
for i in range(1,5):
  print("i=", i)

#Caso 3
print("#Caso 3")
for i in range(1,5,2):
  print("i=", i)

notas = [3.5, 4.2, 2.8, 5.0]

for nota in notas:
    print("La nota es:", nota)

notas = [3.5, 4.2, 3, 5.0]
suma = 0
for nota in notas:
    suma = suma + nota
print("Promedio:", suma / len(notas))

edad = int(input("Tu edad: "))

while edad < 1 or edad >50:
    print("Eso no es válido")
    edad = int(input("Tu edad: "))
print("Bienvenido")

"""Ejercicios de clase

Ejercicio 1. Clasificador de edad (int)

Tipo de dato: entero (int)
Enunciado: Solicita al usuario su edad y clasifícalo en una de las siguientes categorías: niño (0 a 12 años), adolescente (13 a 17 años), adulto (18 a 59 años) o adulto mayor (60 años o más). Si el usuario ingresa un número negativo, muestra un mensaje de error indicando que la edad no es válida.
Pista de estructura
edad = int(input("Ingrese su edad: "))

if edad < 0:
    print("Edad no válida")
elif edad <= 12:
    print("Niño")
    
# completa el resto de condiciones...
Preguntas abiertas
•	1. ¿Qué ocurre si el usuario ingresa un texto (por ejemplo, "quince") en lugar de un número? ¿Por qué crees que sucede eso?
•	2. ¿Por qué es necesario usar int() al capturar la edad y qué pasaría si no lo hicieras?
•	3. ¿Cómo decidiste el orden de tus condiciones (if, elif, else) y por qué ese orden es importante?
"""

edad = int(input("Ingrese su edad: "))

if edad < 0:
    print("Edad no válida")
elif edad <= 12:
    print("Niño")
elif edad <= 17:
  print("Adolescente")
elif edad <= 59:
  print("Adulto")
else:
  print("Adulto mayor")

"""Ejercicio 2. Evaluador de nota final (float)

Tipo de dato: decimal (float)
Enunciado: Pide al usuario su nota final del curso (escala 0.0 a 5.0). El programa debe indicar si el estudiante "Aprobó" (nota mayor o igual a 3.0), está en "Habilitación" (nota entre 2.5 y 2.99) o "Reprobó" (nota menor a 2.5). Además, si la nota ingresada es mayor a 5.0 o menor a 0.0, el programa debe informar que el valor está fuera de rango.
Pista de estructura
nota = float(input("Ingrese su nota final (0.0 a 5.0): "))

if nota < 0.0 or nota > 5.0:
    print("Valor fuera de rango")
elif nota >= 3.0:
    print("Aprobó")
# completa el resto de condiciones...
Preguntas abiertas
•	1. ¿Qué diferencia práctica encuentras entre trabajar con int en el ejercicio 1 y con float en este ejercicio? Menciona un riesgo propio de los números decimales.
•	2. ¿Por qué se debe validar primero el rango fuera de límites (menor a 0.0 o mayor a 5.0) antes que las demás condiciones?
•	3. Si cambiaras el límite de habilitación a 2.6, ¿qué línea de tu código modificarías y qué impacto tendría en los resultados?
Respuesta:

"""

nota = float(input("Ingrese su nota final (0.0 a 5.0): "))

if nota < 0.0 or nota > 5.0:
    print("Valor fuera de rango")
elif nota >= 3.5:
    print("Aprobó")
elif nota >= 2.3:
    print("Habilitacion")
else:
    print("Reprobo")

"""Ejercicio 3. Validador de usuario (str)

Tipo de dato: cadena de texto (str)
Enunciado: Solicita al usuario que ingrese su rol dentro de un sistema académico, escribiendo una de estas opciones: "estudiante", "docente" o "administrador". El programa debe mostrar un mensaje distinto de bienvenida según el rol ingresado, y si el texto no coincide con ninguna opción válida (sin importar mayúsculas o minúsculas), debe indicar "Rol no reconocido".
Pista de estructura
rol = input("Ingrese su rol (estudiante/docente/administrador): ")

if rol == "estudiante":
    print("Bienvenido/a estudiante")
# completa el resto de condiciones...
Preguntas abiertas
•	1. ¿Para qué sirven los métodos .lower() y .strip() aplicados sobre el texto ingresado? ¿Qué problema evitan?
•	2. ¿Por qué comparar cadenas de texto exige más cuidado que comparar números? Da un ejemplo concreto con este ejercicio.
•	3. ¿Cómo modificarías el programa para que también acepte "Estudiante" con tilde o con espacios adicionales al inicio o al final?
Respuesta:


"""

rol=input("ingrese su rol(estudiante/docente/administrador):")
print(rol)

rol=rol.lower().strip()
print(rol)


if (rol=="estudiante"  or rol=="estudianté"):
   print("Bienvenido/a estudiante")
elif rol==("docente"):
   print("Bienvenido/a docente")
elif rol==("admnistrador"):
   print("Bienvenido/a administrador")
else:
   print("Rol no reconocido")

"""Ejercicio 4. Calculadora de índice de masa corporal (float)

Tipo de dato: decimal (float), con dos entradas
Enunciado: Pide al usuario su peso en kilogramos y su estatura en metros. Calcula el IMC con la fórmula IMC = peso / (estatura ** 2) y clasifica el resultado en: "Bajo peso" (menor a 18.5), "Peso normal" (18.5 a 24.9), "Sobrepeso" (25.0 a 29.9) u "Obesidad" (30.0 o más).
Pista de estructura
peso = float(input("Ingrese su peso en kg: "))
estatura = float(input("Ingrese su estatura en metros: "))
imc = peso / (estatura ** 2)

if imc < 18.5:
    print("Bajo peso")
# completa el resto de condiciones...
Preguntas abiertas
•	1. Este ejercicio usa dos valores de entrada para tomar una sola decisión. ¿Qué otras situaciones de la vida real conoces donde se necesiten varias variables antes de decidir algo?
•	2. ¿Qué pasaría en tu programa si el usuario ingresa una estatura de 0? Explica por qué ocurre y cómo lo evitarías.
•	3. ¿Consideras que esta clasificación por rangos numéricos es siempre justa o suficiente para evaluar la salud de una persona? Justifica tu respuesta.
Respuesta:

"""

peso = float(input("ingresa el peso en kg: ") )
estatura = float(input("ingresa la estatura en centimetros: "))
if estatura <= 0:
  print("fuera de rango")
else:

  imc = peso /(estatura**2)


  if imc < 18.5:
    print("Bajo peso")
  elif imc <= 24.9:
    print("peso normal")
  elif imc <= 29.9:
    print("sobrepeso")
  elif imc >= 30:
    print("obesidad")

"""Ejercicio 5. Calculadora de descuento con confirmación (bool a partir de str)

Tipo de dato: texto convertido a valor lógico (bool) + float
Enunciado: Un almacén ofrece 15% de descuento a estudiantes y 5% adicional si la compra supera $200.000. Pide al usuario el valor de su compra (float) y si es estudiante, respondiendo "si" o "no" (texto). Convierte esa respuesta a un valor booleano (por ejemplo, es_estudiante = respuesta.lower() == "si") y usa condicionales para calcular y mostrar el valor final a pagar.
Pista de estructura
compra = float(input("Ingrese el valor de la compra: "))
respuesta = input("¿Es estudiante? (si/no): ")
es_estudiante = respuesta == "si"

descuento = 0.0
if es_estudiante:
    descuento += 0.15
# agrega la condición del descuento adicional...
Preguntas abiertas
•	1. ¿Por qué se dice que la variable es_estudiante es de tipo bool aunque el usuario haya escrito una palabra ("si" o "no") y no True/False directamente?
•	2. ¿Qué pasaría si en el segundo descuento usas un if independiente en lugar de un elif? ¿Cambiaría el resultado final? Explica con un ejemplo numérico.
•	3. Diseña un caso de prueba (valores de entrada) donde se apliquen ambos descuentos y otro caso donde no se aplique ninguno. Escribe los resultados esperados.
Respuesta:

"""

compra = float(input("Ingrese el valor de la compra: "))
respuesta = input("¿Es estudiante? (si/no): ").strip().lower().replace("í", "i")
es_estudiante = respuesta == "si"

descuento = 0.0
if es_estudiante:
    descuento += 0.15
    if compra >= 200000:
        descuento += 0.05
    elif compra >= 300000:
        descuento += 0.07

#Cálculo total
total_descuento = descuento * compra

print(f"El total de la compra es: {compra - total_descuento}")

print("10"+5)

promedio = 3.0
asistencia=80

if(promedio>=3.0) == (asistencia>=80):
  print("valor")

"""# Clase 05/10 - Listas

Enunciado
Doña Marta tiene una tienda de barrio y recibe pedidos por WhatsApp. Para no perder el hilo, guarda cada pedido en una sola lista con estos datos, en este orden: el nombre del cliente (texto), el número de productos (entero), el total a pagar (decimal), si ya pagó (verdadero o falso) y la dirección de entrega (texto). El pedido de hoy es el de Laura:
pedido = ["Laura Gómez", 3, 45500.0, False, "Calle 45 #12-30"]
Durante la mañana el pedido va cambiando y doña Marta necesita que tu programa lo vaya actualizando sobre la misma lista, sin volver a crearla desde cero. Sigue las instrucciones en orden y usa un print para mostrar el resultado de cada paso.
Qué debe hacer tu programa
1. Crea la lista e imprime el nombre del cliente (índice positivo) y la dirección de entrega (índice negativo, sin contar cuántos elementos hay).
2. Laura agregó dos productos más y el total subió a $62.300. Además, ya pagó por transferencia. Corrige esos tres datos directamente en sus posiciones.
3. Doña Marta quiere guardar el teléfono de Laura, "3001234567" (como texto), justo después del nombre, y el nombre del domiciliario, "Andrés", al final de la lista.
4. Agrega al final la hora estimada de entrega: 10 (hora) y 30 (minutos), cada uno como un elemento independiente de la lista. Imprime la lista completa y cuántos elementos tiene.
5. Usando :, imprime en un print distinto cada uno de estos cortes: (a) nombre y teléfono; (b) número de productos, total y estado de pago; (c) los tres últimos datos; (d) toda la lista en orden inverso.



Preguntas trampa
A. Un compañero resolvió el paso 4 con otra instrucción y su lista quedó con 8 elementos en vez de 9. ¿Qué hizo diferente y qué obtiene al imprimir el último elemento de su lista?

B. Otro compañero, ya hecho el paso 3, escribe pedido[4] esperando obtener la dirección de entrega. ¿Qué valor y de qué tipo recibe realmente, y por qué dejó de ser la dirección?
"""

#PUNTO 1
#pedido = [nombre-0 , productos-1, totalpagar-2, yapago-3, direccion-4]
pedido = ["Laura Gómez", 3, 45500.0, False, "Calle 45 #12-30"]

#Lista creada ok

print("Nombre cliente: ", pedido[0])
print("Direccion: ", pedido[-1])

#PUNTO 2
pedido[1]=pedido[1]+2
print(pedido)
pedido[1]=5
print(pedido)

pedido[2]=62300.0
pedido[3]=True

print(pedido)

#PUNTO 3
pedido.insert(1, "3001234567")
print(pedido)

pedido.append("Andrés")
print(pedido)

#PUNTO 4
pedido.append([10,30])
print(pedido)
print(len(pedido))

#PUNTO 5
print("Primer mensaje")
print(pedido[:2])
print("Segundo mensaje")
print(pedido[2:5])
print("Tercero mensaje")
print(pedido[-3:])

print("Cuarto mensaje")
print(pedido[::-1])

listaNumeros = [5,"hola",True,200]

print(listaNumeros)

for paola in listaNumeros:
  print(paola)

print("lista numeros: ", len(listaNumeros))

for i in range(1,4,2):
  print("listaNumeros[",i,"]=", listaNumeros[i])

thislist = ["apple", "banana", "cherry"]
i = 0
print(i)
while i < len(thislist):
  print(i , "<",len(thislist) )
  print("thislist[",i,"]=", thislist[i])

  i = i + 1
  print("i=i+1 -> i:", i)